---
title: "Workspace"
author: "Pouya Mohammadi"
date: "3/22/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The EDA is a bit strange in terms of the conditioning - you are looking within counties' political leanings. But would it make more sense to display, given a county has each type of score, the proportion that were Democrat vs. Republican? As well, I suspect that there are much more Republican counties than Democrat counties, though population-wise they are much more similar. These relationships are lost in the EDA, since only proportions are shown. Consider examining absolute population- or county-level counts as well.

^^ ASK ABOUT THIS. NOT SURE WHAT THIS MEANS


# Takeaways

Something about how this could be similar to the waffle house index but for politics

# Limitations

Talk about how using percentage of democratic votes is valid since the US is largely a 2 party system. However, this does not account for the maximum <5% of votes in a county that are given to 3rd party candidates and could cause problems, since we sort of make the assumption that gop and dem are the only ones that get votes.